name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'create env file'
        run: |
          cat > .env.production << 'EOF'
          ${{ secrets.TWITTER_ENV_PRODUCTION }}
          EOF
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ken/twitter:v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Tag Docker image
        run: docker tag ken/twitter:v4 kenn0679/twitter-clone-project:v4
      - name: Push the Docker image
        run: docker push kenn0679/twitter-clone-project:v4
